version: "3.9"

services:
  app:
    container_name: mulo-web-prod
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    expose:
      - "80"
    restart: always
    volumes:
      - ./nginx/conf/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mulo-shared-net
networks:
  mulo-shared-net:
    external: true
